In [1]:
# load in NumPy
import numpy as np

### Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[3.4,1.2,4.5],[1,3,5]])
print(b)

[[3.4 1.2 4.5]
 [1.  3.  5. ]]


In [4]:
# get dimension
a.ndim

1

In [5]:
# get shape
b.shape

(2, 3)

In [6]:
# get type
a.dtype

dtype('int32')

In [7]:
# get size
# it is no. of bytes. here int32 so 4 bytes
a.itemsize

4

In [8]:
# get total size
# it is equal to no. of items * a.itemsize
a.size*a.itemsize

12

In [9]:
# we can change data type of a
a = np.array([1,2,3], dtype='int16')
a.dtype

dtype('int16')

In [10]:
a.itemsize

2

In [11]:
b.itemsize

8

In [12]:
b.dtype

dtype('float64')

### Accessing/Changing specific elements,rows,columns,etc

In [13]:
c = np.array([[1,3,2,4,6,1,2],[2,3,5,9,1,6,9]])
print(c)

[[1 3 2 4 6 1 2]
 [2 3 5 9 1 6 9]]


In [14]:
# get a specific element [r, c] 
# let say we have to get 5
c[1, 2]

5

In [15]:
# get a specific row
c[0, :]       # here first row

array([1, 3, 2, 4, 6, 1, 2])

In [16]:
print(c[0, :])

[1 3 2 4 6 1 2]


In [17]:
# get a specific column
print(c[:, 2])


[2 5]


In [18]:
# get a little more fancy [start index:end index:step size]      
# end index is exclusive
c[0,1:5:2]

array([3, 4])

In [19]:
# to change a specific element
c[1,2] = 10
print(c)

[[ 1  3  2  4  6  1  2]
 [ 2  3 10  9  1  6  9]]


In [20]:
# to change a column
c[:, 2] = 5
print(c)

[[1 3 5 4 6 1 2]
 [2 3 5 9 1 6 9]]


In [21]:
c[:, 2] = [2,5]
print(c)

[[1 3 2 4 6 1 2]
 [2 3 5 9 1 6 9]]


In [22]:
d = np.array([[[1,3],[2,4]],[[4,6],[9,8]]])
print(d)

[[[1 3]
  [2 4]]

 [[4 6]
  [9 8]]]


In [23]:
# get specific element (work outside in)
d[0,1,1]

4

In [24]:
d[:,1,:]

array([[2, 4],
       [9, 8]])

In [25]:
d[:,0,:] = [[2,4],[3,4]]
d

array([[[2, 4],
        [2, 4]],

       [[3, 4],
        [9, 8]]])

### Intializing different types of Arrays

In [26]:
# all 0s matrix
np.zeros(3)


array([0., 0., 0.])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [29]:
# all 1s matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
# any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [32]:
# any other number i.e to use shape of previous matrix, let say c matrix
np.full(c.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [33]:
# or
np.full_like(c,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
# random decimel number
np.random.rand(3,5)

array([[0.19468381, 0.4654597 , 0.01520648, 0.03458746, 0.78133663],
       [0.81281989, 0.42426395, 0.54776091, 0.75306282, 0.17039134],
       [0.78739612, 0.88257187, 0.64441012, 0.02085708, 0.62970765]])

In [35]:
np.random.random_sample(c.shape)

array([[0.2902756 , 0.72868549, 0.41588047, 0.28269411, 0.42912103,
        0.00305795, 0.18049859],
       [0.38976684, 0.31989483, 0.05186415, 0.35087303, 0.11334941,
        0.35521666, 0.50977531]])

In [36]:
# random integer values
np.random.randint(2,6, size=(3,3))
# any no. btw 2 and 6. 6 is exclusive

array([[5, 2, 3],
       [2, 5, 2],
       [2, 4, 5]])

In [37]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [39]:
arr = np.array([[1,2,3]])
# make 2d array in above
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
# print the matrix drawn in copy
e = np.ones((5,5))
f= np.zeros((3,3))
f[1,1] = 9
e[1:4,1:4] = f
print(e)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
# to copy one array to another
g = np.array([1,2,3])
h = g
print(h)

[1 2 3]


In [42]:
g = np.array([1,2,3])
h = g
h[0] = 100
print(h)

[100   2   3]


In [43]:
# here h = g means h and g are same. so changing  h will cause change in g
g = np.array([1,2,3])
h = g
h[0] = 100
print(g)

[100   2   3]


In [44]:
g = np.array([1,2,3])
h = g.copy()  # to overcome problem of h = g
h[0] = 100
print(h)

[100   2   3]


In [45]:
g = np.array([1,2,3])
h = g.copy()
h[0] = 100
print(g)

[1 2 3]


### Mathematics

In [46]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [47]:
a+5

array([ 6,  7,  8,  9, 10])

In [48]:
a-2

array([-1,  0,  1,  2,  3])

In [49]:
a*2

array([ 2,  4,  6,  8, 10])

In [50]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [51]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [52]:
b = np.array([5,4,3,2,1])
a+b

array([6, 6, 6, 6, 6])

In [53]:
# take the sin or cosine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [54]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

   #### Linear Algebra

In [55]:
# to multiply two matrix
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [56]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [57]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [58]:
# finding determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

1.0

In [59]:
d = np.matmul(a,b)
np.linalg.det(d)

0.0

In [60]:
## reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
# determinant
# trace
# singular vector decomposition
# Eiganvalues
# matrix norm
# inverse
# etc

### Statistics

In [61]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [62]:
np.min(a)

1

In [63]:
np.max(a)

6

In [64]:
# min all rows
np.min(a, axis = 1)

array([1, 4])

In [65]:
# min along coloumns
np.min(a, axis = 0)

array([1, 2, 3])

In [66]:
# sum of all elements
np.sum(a)

21

In [67]:
# sum along rows
np.sum(a, axis=1)

array([ 6, 15])

### Reorganizing arrays

In [68]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [70]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [71]:
# vertically stacking vectors
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b,a,b,a))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [73]:
# horizontally stacking vectors
a = np.ones((2,4))
b = np.zeros((2,2))
np.hstack((a,b))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Loading data from file

In [74]:
file = np.genfromtxt('data.txt',delimiter=',')
file

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [75]:
file.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

##### Boolean masking and advanced indexing

In [76]:
file > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [77]:
file[file > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [78]:
# you can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [79]:
np.any(file > 50, axis=0)
# any along first coloumn is > 50, along 2nd coloumn > 50 and so on

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [80]:
np.all(file > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [81]:
np.any(file > 50, axis=1)

array([ True,  True,  True])

In [82]:
(file > 50)&(file < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [83]:
~(file > 50)
# not = ~

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [84]:
a=np.arange(2,5)
print(a)

[2 3 4]
